import type { Metadata } from 'next';
// fonts
import { alegreyaSans } from '@/app/fonts';
// global styles
import './globals.css';

// ----------------------------------------------------------------------

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={alegreyaSans.className} suppressHydrationWarning>
        {children}
      </body>
    </html>
  );
}
